import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import WhatsApp from "@/components/contactwp";
import Insta from "@/components/contactinsta";

const inter = Kanit({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Core Fit Gym",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={inter.className}>
        <Header><> {/*header*/}</></Header>
        {children}
        <Insta><></></Insta>
        <WhatsApp><></></WhatsApp>
        <Footer><> {/*footer*/}</></Footer>
      </body>
    </html>
  );
}
